package com.hwqgooo.douknow.model.dao;

import org.greenrobot.greendao.annotation.Entity;
import org.greenrobot.greendao.annotation.Generated;
import org.greenrobot.greendao.annotation.Id;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "DAILY_ORM".
 */
@Entity
public class DailyORM {

    @Id
    private Long dailyid;

    @Generated(hash = 1401739712)
    public DailyORM() {
    }

    @Generated(hash = 170504261)
    public DailyORM(Long dailyid) {
        this.dailyid = dailyid;
    }

    public Long getDailyid() {
        return dailyid;
    }

    public void setDailyid(Long dailyid) {
        this.dailyid = dailyid;
    }

}
